### PR TITLE
Prepares v0.10.0 release

### PR DESCRIPTION
**Pull request by johnedquinn**
## Relevant Issues
- None

## Description
- Prepares v0.10.0 release
  - Copied and pasted the CHANGELOG for v0.9.3 and updated v0.9.4 as well.

## Follow-Ups
- Created #1067 to track migration guide release

## Other Information
- Updated Unreleased Section in CHANGELOG: **YES**
- Any backward-incompatible changes? **NO**
  - This is a release
- Any new external dependencies? **NO**

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by am357** [comment]
Thanks for this, can we also add the output of `japi-compliance-checker` to the PR?

**Review by yliuuuu — APPROVED** [review]

**Comment by alancai98** [comment]
Probably worth also tracking in an issue that we should add a migration guide between v0.9.* and v0.10.0.

**Comment by am357** [comment]
[compat_report.html.zip](https://github.com/partiql/partiql-lang-kotlin/files/11410465/compat_report.html.zip)

**Comment by johnedquinn** [comment]
> Probably worth also tracking in an issue that we should add a migration guide between v0.9.* and v0.10.0.

@alancai98 Good idea -- created #1067

> Thanks for this, can we also add the output of `japi-compliance-checker` to the PR?

@am357 Unfortunately, GH doesn't allow you to add HTML files as attachments. But, I've sent offline. The JAPI report actually did remind me to update the CHANGELOG to reflect the mix-up from the earlier, accidental release of v0.9.3.

**Review by am357 — APPROVED** [review]

**Pull request merged**
