### PR TITLE
Standardize PartiQL builtins and implement POSITION and OVERLAY

### PR DESCRIPTION
**Pull request by RCHowell**
## Description

This PR implements all builtins as internal singletons and mostly standardizes their implementation. The idea here is to get our existing functions to _look_ like libraries as we discuss expansions to the builtins in the global namespace or perhaps as a library. The builtins have been separated into three pseudo-libraries

1. ScalarBuiltinsSql — builtins from SQL-99 feature table
2. ScalarBuiltinsExt — extra builtins added to PartiQL which are not in the SQL standard
3. ScalarBuiltinsCollAgg — collection aggregations from the PartiQL Specification

## Action Items

Some work was left out of this PR to keep the review streamline and reviewers sane. Very little business logic was changed for existing functions. Additional work that will be done in subsequent PRs is

- [ ] Statistical aggregation functions
- [ ] Function lowering
- [ ] Substring pattern (defined in spec, missing as of now)
- [x] Update external documentation
- [x] Add OVERLAY tests to the conformance test suite

The final note on documentation is in regards to our functions wiki page. We have valuable code comments that aren't visible to PartiQL users because the comments are on internal classes and therefore never make it to the public docs. Either we process these to generate functions.md, or we copy-paste all existing internal documentation comments. I'd prefer the former approach of generating documentation, but understandable if this is not practical from a time constraint.

## Other Information
- Updated Unreleased Section in CHANGELOG: **[YES/NO]**
Yes. Added a note about the new functions

- Any backward-incompatible changes? **[YES/NO]**
TODO need to confirm whether or not any visibility modifiers were changed

- Any new external dependencies? **[YES/NO]**
No

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jpschorr** [comment]
Probably worth pulling in the latest https://github.com/partiql/partiql-tests/ as it includes your tests for these functions in the conformance runner

**Review by jpschorr — APPROVED** [review]
Looks good. I'd like to see the latest partiql-tests pulled in here and the conformance run for the CI build.

**Review by vgapeyev — APPROVED** [review]
More consistency among built-in definitions is great!

Just a few documenting suggestions, in case this gets to you before merging.

**Review by vgapeyev — APPROVED** [review]
Trusting that any new changes in the rebase merely straightforwardly address the comments from the PR reviews.

**Pull request merged**
