### PR TITLE
Remove redundancy by using ANY parameter for IS TYPE operators

### PR DESCRIPTION
**Pull request by RCHowell**
## Relevant Issues
N/A

## Description
Reduces redundancy of the IS TYPE operators as they do not need to be defined for each individual type.

## Other Information
- Updated Unreleased Section in CHANGELOG: **[YES/NO]**
No

- Any backward-incompatible changes? **[YES/NO]**
  - < If YES, why? >
  - < For this purpose, we define backward-incompatible changes as changes that—when consumed—can potentially result in
errors for users that are using our public APIs or the entities that have `public` visibility in our code-base. >
No, internal typer concern for 0.14

- Any new external dependencies? **[YES/NO]**
  - < If YES, which ones and why? >
  - < In addition, please also mention any other alternatives you've considered and the reason they've been discarded >
No

- Do your changes comply with the [Contributing Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CONTRIBUTING.md)
  and [Code Style Guidelines](https://github.com/partiql/partiql-lang-kotlin/blob/main/CODE_STYLE.md)? **[YES/NO]**
Yes

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yliuuuu** [comment]
One thing that may cause us trouble is `missing` handling. 

In other functions, for example `1+missing`, will be rewrite to `plus(1, missing)` and the function would not be resolved. That is, in most of the functions where `missable` is true, the handling strategy is to not resolve the function at the first place. 

With this change, `MISSING IS INT2` will be resolved to `is_int2(missing)`, such function can be resolved due to the value argument being `ANY` in the header. In the typer we then raise a `expression always returns missing` error. 

This is more of a inconsistence than a problem, but it is worth to consider as change of errors may affect our customers.

**Comment by RCHowell** [comment]
I wonder if this handles it though? https://github.com/partiql/partiql-lang-kotlin/blob/c73efbf3f1e96856c718a359771b2ffff91fb61c/partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt#L654-L660

I feel the only issue here will be `is_missing` which I need to add a case for.

**Comment by yliuuuu** [comment]
> I wonder if this handles it though?
> 
> https://github.com/partiql/partiql-lang-kotlin/blob/c73efbf3f1e96856c718a359771b2ffff91fb61c/partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt#L654-L660
> 
> I feel the only issue here will be `is_missing` which I need to add a case for (spec page 30).

The code snippet you show raised a `alwaysMissing` problem and return a resolved function whose return type is `missing`. 

I tried to point out that for other functions, the issue raised is going to be a `unresolved function`. See 
https://github.com/partiql/partiql-lang-kotlin/blob/c73efbf3f1e96856c718a359771b2ffff91fb61c/partiql-planner/src/main/kotlin/org/partiql/planner/internal/typer/PlanTyper.kt#L619-L640

**Review by yliuuuu — APPROVED** [review]
Approving this PR based on offline discussion. We are going to further investigate on MISSING.

**Pull request merged**
