### PR TITLE
Makes SqlException.errorContext non-nullable, resolving Issue #616.

### PR DESCRIPTION
**Pull request by vgapeyev**
## Relevant Issues
- Closes Issue #616

## Description

This is a simple PR: There was an in-code TODO at SqlException, pointing at Issue #616.
The suggestion was to change the field to non-nullable, switching from null to an empty PropertyValueMap as the declared default.  It turned out that many use sites have already provided non-null actuals, so even a default is not necessary in a few places.  The only subclass that had use sites with null actuals (coming through the default) was EvaluationException, so its default did get changed rather than removed. 

## Other Information
- Updated Unreleased Section in CHANGELOG: **[NO]**
  - This is an internal change.
- Any backward-incompatible changes? **[NO]**
- Any new external dependencies? **[NO]**

## License Information

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RCHowell** [comment]
Looks good to me, but I'm curious why the partiql-tests git module was included? Perhaps you can do `git submodule update --init` and update the PR?

**Comment by vgapeyev** [comment]
> 

Not sure what is going on with the submodule.  If it has been introduced recently, I must have missed the memo on how to deal with it.  

Here is what happened on my side, if anyone can do the forensics: I started this PR off main, before 55de0988 came in (which had a change in test/partiql-tests). After that, I pulled myself up on main, branched and committed.  Looking at the history, this commit reverted what 55de0988 did in test/partiql-tests. Why? -- someone with better understanding of git is needed. With "regular" files the above workflow did not give me grief before.

At this point, the suggested `git submodule update --init` did not have a detectable effect.  
I think I'll just revert the revert that I see in test/partiql-tests and hope for the better.

**Comment by vgapeyev** [comment]
Well `git restore --source 55de0988 test/partiql-tests` did not have a visible effect either.  

@alancai98 do you have any suggestions?

Otherwise, not understanding what is gong on, I'd just cancel this PR and do a new one with the same delta.

**Comment by alancai98** [comment]
> Well `git restore --source 55de0988 test/partiql-tests` did not have a visible effect either.  
@alancai98 do you have any suggestions?
Otherwise, not understanding what is gong on, I'd just cancel this PR and do a new one with the same delta. 

I'm not sure why Robert's suggested command doesn't work to update the git submodule. An alternative is to manually go to the submodule and pull in the latest changes: i.e.

1. `cd test/partiql-tests`
2. `git pull`

Alternatively from the root directory, I think you can run `git submodule foreach git pull origin main` to have each submodule update with what's in `main`.

**Comment by vgapeyev** [comment]
@RCHowell , @alancai98 thanks for the catch and for the assistance.  The diff looks as expected now.

**Review by alancai98 — APPROVED** [review]

**Pull request merged**
